name = "Contexts"
uuid = "f9ffe950-3109-4ed3-b2df-b0b3d544a50d"
authors = ["emmac <emmettgb@gmail.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Toolips = "a47e2ad8-fcf7-417c-9746-32b9bdf220bd"
ToolipsSVG = "8ae86ec9-919d-4ece-9a6d-09b7d28dae11"
